<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [2]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(ax,id(ax),len(ax))
type(ax)

[1 2 3 4 5] 1858864282960 5


numpy.ndarray

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [4]:
x=['1','2','3']
print(type(x))
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')
print(type(xi))

<class 'list'>
[1 2 3]
[1. 2. 3.]
['1' '2' '3']
<class 'numpy.ndarray'>


<h2>Basic operations</h2>

In [5]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h2>Multi-dimensional arrays</h2>

In [6]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [9]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [10]:
ax[1:3,2:4]
#ax[:,2:]

array([[12., 13.],
       [22., 23.]])

<h3>Reshaping</h3>


In [12]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3)

(3, 6)


ValueError: cannot reshape array of size 18 into shape (10,3)

<h3>Creating initialized arrays</h3>

In [13]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [ ]:
ax = np.ones(10)
print(ax)

In [ ]:
ax = np.arange(10)**2
print(ax)

In [14]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<h3>Matrix multiplication</h3>


In [ ]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

In [ ]:
np.dot(ay,ay.reshape(10,2)) #Dot product

<h3>Comparing numpy arrays with lists</h3>

In [26]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
#print(ax)
#print(ay)
np.dot(ax,ay)

array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

<h4>Functionalize this</h4>


In [25]:
ax = np.array([np.arange(10)**2,np.arange(10)**3])
ay = ax.transpose()
print(ax)
print(ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


In [21]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    print(ay)
    print(ax)
    
dotproduct(10) 
#El resultado es el tiempo que tarda en hacer la multiplicación de la matriz y su traspuesta


datetime.timedelta(0)

<h4>Do the same with python lists</h4>


In [28]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]#otra manera de trasponer
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]#otra manera de multiplicar np.dot()
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10000)

datetime.timedelta(microseconds=12965)

In [29]:
for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')
#Numpy mejora los tiempos de computo

10	0:00:00	0:00:00
100	0:00:00	0:00:00.000995
1000	0:00:00	0:00:00.414811
10000	0:00:00	0:00:00.029921


<h3>Selecting elements from an np array</h3>

In [30]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [ ]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [ ]:
#BORRAR, EN EL VIDEO LO IGNORA
import scipy
scipy.nanmean(x)

<h3>Random number support in numpy</h3>

In [32]:
#np.random.normal(size=10)
np.random.normal(size=(5,5))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([[ 1.29275661, -1.34232846,  0.36670667,  1.09604943, -0.95540994],
       [ 0.20876588, -0.84899348, -1.60685131, -1.51770515,  0.3990441 ],
       [-0.94766321,  1.42297935,  1.23614684, -0.99922338, -0.82239004],
       [-1.98466342,  0.47846663,  1.5363416 ,  0.48771863,  0.40910034],
       [ 2.68746971,  1.47531918, -0.49980878,  0.78990163,  0.79135038]])